#!/bin/sh

matches_semver() {
  #REGEX="\d+\.\d+\.\d+(\-[0-9a-f]{0,40})?"
  echo "test $1"
  #if [[ "$1" =~ $REGEX ]]; then
  #if [[ "$1" =~ '\d+\.\d+\.\d+\(\-[0-9a-f]{0,40}\)?' ]]; then
  if [[ "$1" =~ [0-9]+\.[0-9]+\.[0-9]+(-[0-9a-f]{0,40})? ]]; then
    # 0 = true
    return 0
  else
    # 1 = false
    return 1
  fi
}
matches_semver "11.13.2"
set -u
matches_semver "1.1.1-abc"
if [ -n "${TRAVIS_TAG}" ]; then
  TRAVIS_SEMVER="$(matches_semver "${TRAVIS_TAG}")"
  if [ "$?" -ne 0 ]; then
    echo "TRAVIS_TAG ${TRAVIS_TAG} does not follow semver" 1>&2
    exit 1
  fi
  PACKAGE_VERSION="$(xmllint --nsclean --xpath '/project/version/text()' pom.xml)"
  PACKAGE_SEMVER="$(matches_semver "${PACKAGE_VERSION}")"
  if [ "$?" -ne 0 ]; then
    echo "version ${PACKAGE_VERSION} in pom.xml does not follow semver" 1>&2
    exit 1
  fi
  if [ "${TRAVIS_TAG}" != "${PACKAGE_VERSION}" ]; then
    echo "According to semver, TRAVIS_TAG ${TRAVIS_TAG} differs from version ${PACKAGE_VERSION} in pom.xml" 1>&2
    exit 1
  else
    echo "Travis tag and pom.xml versions match"
  fi
fi
